# Netlify configuration

[build]
  functions = "netlify/functions"
  publish = "public"

[dev]
  publish = "public"

# This now correctly includes the key file from the root directory
[functions]
  included_files = ["digiworld-46a1e-firebase-adminsdk-fbsvc-5542dd28ef.json"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions."check-stock"]
  schedule = "0 9 * * *"