# Netlify configuration

[build]
  functions = "netlify/functions"
  publish = "public"

[dev]
  publish = "public"

# This section tells Netlify to include our secret key file with the functions
[functions]
  included_files = ["netlify/functions/*.json"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions."check-stock"]
  schedule = "0 9 * * *"