# Netlify configuration

[build]
  functions = "netlify/functions"
  publish = "public"

[dev]
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# NEW: Scheduled function for stock checking
[functions."check-stock"]
  # This cron expression means "at 9:00 AM UTC every day".
  # You can change the schedule if you like.
  schedule = "0 9 * * *"
