# netlify.toml

[build]
  # This is the directory where your static site files (HTML, CSS, JS) are located
  publish = "public"
  # This is the directory where your Netlify Functions are located
  functions = "netlify/functions"

[functions]
  # Optional: Use esbuild for faster function builds (recommended)
  node_bundler = "esbuild"
  # Optional: Specify the Node.js version to use for your functions
  # Ensure this matches your development environment or a compatible version (e.g., "18" or "20")
  node_version = "20" 
